### ISSUE TITLE
Build development environment?

### ISSUE THREAD

**Issue by tfrijsewijk** [osdevisnot/klap#292]
Hi!

I'm developing a library and I would like to publish the development environment as a static site.

Any suggestions?

Thanks!

**Comment by osdevisnot** [comment]
👋 @tfrijsewijk The common requirements for building a static sites depends on what you are building. The javascript ecosystem offers a lot of options to get started. Some of which are available here: https://jamstack.org/generators/

PS: I am closing this issue since it's not related to klap. We can always comment on close issue for additional information/questions.

**Comment by tfrijsewijk** [comment]
Thanks for replying! I know about static site generators, but I'm specifically talking about the development environment that's started with `klap start`.

In my example, I'm developing a Leaflet.js plugin using klap which I'm publishing to NPM. I have my dev environment set up with Leaflet and a configured map. This works great, of course: Watching, live reload, mocked data, etc. It would be great if I could use it as an example page: always up to date and no overhead of maintaining a seperate example site.

Any thoughts?
