### ISSUE TITLE
Question: ncc vs rollup

### ISSUE THREAD

**Issue by dnl-brnr** [osdevisnot/klap#33]
@osdevisnot 

I'm curious about the choice to use ncc vs Rollup to compile klap. What are the differences/advantages? Do you have any idea about how they compare in terms of tree-shaking?

**Comment by osdevisnot** [comment]
Most of Dev dependencies we use with klap are authored as commonjs modules. I find rollup to be a bit of pain for commonjs deps. Whereas ncc uses webpack which handled commonjs pretty well. However, I'm pretty sure rollup would offer much better tree shaking.

TLDR; we use ncc mostly because it's convenient.

**Comment by dnl-brnr** [comment]
I see. I too have struggled recently with rollup and cjs deps. I assumed that I just didn't understand rollup well enough, which may very well be the case. 

The primary reason I ask is because I'd be reluctant to add any additional devDeps in a PR if I wasn't 100% sure they'd be fully tree-shaken. I don't know to what degree you're concerned about klap's bundle size.

**Comment by osdevisnot** [comment]
TBH we don't want to have a hard limit on bundle size as long as its reasonable. In my mind, it needs to be correct value prop for the project. 
For eg: I would hesitate to add any additional dependency for `init`, but can take few MBs if we find a better minifier than `terser`.

**Comment by osdevisnot** [comment]
NB: I did not mean `terser` is not good at minifying. I was just trying to make up an example.

**Comment by tunnckoCore** [comment]
@dnl-brnr ncc/webpack is great for CLIs and apps. Rollup has some problems with CJS, some times. Or some times it cannot bundle absolutely everything without much work, as webpack does. Everything you throw at Webpack will be bundled without problems - slow, but without problems (totally another talk is if the thing is working). Before few months I tried again to bundle ESLint with Rollup and this try succeed, so things are getting better in Rollup. 

But there are drawbacks with Webpack: 1) Webpack **still** cannot output (proper) ESM. I'm saying "proper" here because there _is_ a way to output ESM (with `@purtuga/esm-webpack-plugin`) but it's not okay for libraries (if you are author of a library) and their consumers. 2) Webpack is kind of oldschool, and wraps every single package/module in a wrapper function, from there comes the above problem. 3) Webpack does tree-shaking (as part of other optimizations?) but only on "prod mode", so you can't see easily what's tree-shaked and what's not in your output, and what's happening in general. 4) bundle sizes are lower with Rollup (and I'm mostly it will always be that way), and that's just because the design and how it works - plus it outputs almost untouched & readable code.

Aside from Webpack problems/drawbacks/minuses, ncc has its own. @ZEIT decline to allow ncc to accept ESM input files (it's actually possible but your deps are resolve from the `main` field, so no tree-shaked) and output ESM. And it's stupid simple change that even won't need huge maintenance or future problems. That's why I forked it and published `@tunnckocore/ncc` from the beginning. But is quite old. And last few months I can even build from master to get tests passing so... I'm in no-mans-land currently. I always gravitated to @Rollup anyway.

**Comment by dnl-brnr** [comment]
@tunnckoCore Thanks for the detailed info. I don't know what I'd do with all my time if I didn't have to always fight with JS build tools...maybe actually build something?😂

**Comment by tunnckoCore** [comment]
@dnl-brnr yea... I miss this time :D `index.js` and `test.js` (+ nyc/istanbul) in the root of the repo, `module.exports`, eslint/airbnb/standard, DONE!

Now... When I jumped on that Babel/esm train before 1-2 years my productivity gone basically to zero. The other problem is that I'm building tools/things with the tools/things I'm building... so it's a bit harder and is one endless circle of jumping between repos, then came the monorepo idea from where are coming couple of more problems... aaaannd.. yea. :rofl:

**Comment by osdevisnot** [comment]
Interesting insight @tunnckoCore. Thank you for taking time to explain in details.

One note on rollup ESM support, the stencil team uses rollup for large parts, and they are helping with the CJS story with rollup. See this - https://twitter.com/manucorporat/status/1213773647896289280?s=19

Also thank you for your words on code structure and style in this repo. The words of encouragement means a lot to me.

**Comment by osdevisnot** [comment]
Closing this for now. feel free to re-open the discussion if needed.
