### ISSUE TITLE
Strange import behaviour on importing external dependency

### ISSUE THREAD

**Issue by marcuslindblom** [osdevisnot/klap#50]
I'm using klap 5.0.0 and I try to build a file that imports idb from unpkg.

This is the script I'm using.

```js
import { openDB } from 'https://unpkg.com/idb/with-async-ittr?module';

const dbPromise = openDB('wieldy', 1, {
  upgrade(db) {
    const userStore = db.createObjectStore('users', {
      keyPath: 'id',
    });    
  },
});

export const db = {
  async setAll(key, users) {
    const tx = (await dbPromise).transaction(key, 'readwrite')
    const store = tx.objectStore(key)

    for await (const user of users) {
      store.put({ ...user })
    }

    await tx.done;

    this.processCallbacks();
  }
};
```
This is my `package.json`.

```json
{
  "name": "idb-import",
  "version": "1.0.0",
  "description": "",
  "source": "index.js",
  "module": "index.esm.js",
  "scripts": {
    "build": "npx klap build",
    "watch": "npx klap watch"
  },
  "devDependencies": {
    "klap": "^5.0.0"
  }
}
```

This is the output from klap:
```bash
klap@5.0.0 - Working on build...
'babel-plugin-transform-async-to-promises/helpers' is imported by index.js, but could not be resolved – treating it as an external dependency
'https://unpkg.com/idb/with-async-ittr?module' is imported by index.js, but could not be resolved – treating it as an external dependency
        368 B   index.esm.js
```
The strange part here is that klap includes `babel-plugin-transform-async-to-promises/helpers` like this.
```js
import{_forAwaitOf as r}from"babel-plugin-transform-async-to-promises/helpers";
```
And that will not work in the browser.

I don't why but klap includes  `babel-plugin-transform-async-to-promises/helpers` when I include this in my script

```js
for await (const user of users) {
    store.put({ ...user })
}
```

**Comment by osdevisnot** [comment]
thank you for the report @marcuslindblom.

I believe `for-await-of` handles sync iterables by converting them to async iterables. So the transformation here is correct. See a reproduction in babel repl [here](https://babeljs.io/en/repl#?browsers=defaults%2C%20not%20ie%2011%2C%20not%20ie_mob%2011&build=&builtIns=false&spec=false&loose=false&code_lz=JYWwDg9gTgLgBAbzhMBTAdgEQEJwL5wBmUEIcA5ABYwxgDOAXAPRMCu6YA1gOYB0AxqSbAAJgCMmAd2AxKAWgCGdAJ7p-cmTCgB-EBBGsANqnIBuAFDnB6OvHEAFEiGB1UcALzI0WbAApy0qiGIsrkADRwAIwRCOZwcKxg3FAKIqi-4gCUiHHxcNa2Ca5QAMow0G6e4gJQqAowqADyYgBWqPwwZRX-rMV04Tl5eZyoyvb1lAwUouG58XiZpkO5eGHmCxbmqAAekLD5EDZ2Yh6DcEqq_HCuMACChoa-I8oRvahQdNmxQwXwMNunXwKSQKGRwBxOFyoTK8LQKGwKDrAQ5PUYRci1VKSKAyEyZOYHI7Xcq1U7_XgQVrtTok9LPfEEwjQc4gsG-X5Fd7IQicj5fAnxWwVXhgVgwXxIXhSt5QfD4oZ4SxDYGgv7bXgiQ6oTZDWQuEUkfioOh0ADCCgeYkRnDovkWK3WpiAA&debug=false&forceAllTransforms=false&shippedProposals=false&circleciRepo=&evaluate=false&fileSize=false&timeTravel=false&sourceType=module&lineWrap=true&presets=env%2Creact%2Cstage-2%2Cenv&prettier=false&targets=&version=7.11.6&externalPlugins=)

as for the externals warning on `babel-plugin-transform-async-to-promises/helpers`, my thought was to keep it untranspiled in library code so that the final application bundle can de-dupe these helpers. 

However, if you wanted to bundle it in, installing the helper in your project should help:
```
yarn add babel-plugin-transform-async-to-promises
```

This will bloat the final bundle size though.

**Comment by marcuslindblom** [comment]
@osdevisnot Ok, It's ok if the dependency is treated as external.
Maybe I wasn’t clear but I try to bundle js modules that should work in the browser.

Using this works in the browser
```js
import { openDB } from 'https://unpkg.com/idb/with-async-ittr?module';

const dbPromise = openDB('wieldy', 1, {
  upgrade(db) {
    const userStore = db.createObjectStore('users', {
      keyPath: 'id',
    });    
  },
});

export const db = {
  async setAll(key, users) {
    const tx = (await dbPromise).transaction(key, 'readwrite')
    const store = tx.objectStore(key)

    for await (const user of users) {
      store.put({ ...user })
    }

    await tx.done;

    this.processCallbacks();
  }
};
```
But after I have used klap. this is added to the beginning of the bundlee `import{_forAwaitOf as r}from"babel-plugin-transform-async-to-promises/helpers";` and my code does not work in the browser anymore. The error is off course.

`Uncaught TypeError: Failed to resolve module specifier "babel-plugin-transform-async-to-promises/helpers". Relative references must start with either "/", "./", or "../".`

Shouldn’t this be possible with klap or do I need to bundle `babel-plugin-transform-async-to-promises/helpers` this my self and not treat it as an external dependency?

**Comment by osdevisnot** [comment]
I think I might have misunderstood your original request. Looking deeper into this, it seems we add `babel-plugin-transform-async-to-promises` dependency even when the browser target is modern. I will fix this in a new release shortly.
